### ISSUE TITLE
Add the missing logic to the Sorting Lambda Skeleton Code

### ISSUE THREAD

**Issue by dbarrous** [HERMES-SOC/sdc_aws_sorting_lambda#1]
**Description:**
Fill out the blanks and complete the logic for the Sorting Lambda Function. 
Repo to function: https://github.com/HERMES-SOC/swsoc-sorting-lambda

**Deliverable:**
Completed Sorting Lambda Function

**Comment by ehsteve** [comment]
See the code being developed in 'hermes_core' in the pull request number 12. It provides a function to detect and parse a hermes file name.
